### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by maheshz09** [lynnaouad/CoffeeShop-Website#1]
hello,

i have done the following steps as mentioned for installation but getting this error, can you please check

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\aa\CoffeeShop\includes\db_connect.php:7 Stack trace: #0 C:\xampp\htdocs\projects\aa\CoffeeShop\includes\db_connect.php(7): mysqli_connect('localhost', 'root', Object(SensitiveParameterValue), 'coffeeshop') #1 C:\xampp\htdocs\projects\aa\CoffeeShop\index.php(56): include_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\projects\aa\CoffeeShop\includes\db_connect.php on line 7

**Comment by krithvikgit** [comment]
hello,

i have done the following steps as mentioned for installation but getting this error, can you please check


Connected successfully to database: coffeeshop
Fatal error: Uncaught mysqli_sql_exception: Table 'coffeeshop.administrator' doesn't exist in C:\xampp\htdocs\CoffeeShop-Website-main\CoffeeShop\admin_panel\index.php:15 Stack trace: #0 C:\xampp\htdocs\CoffeeShop-Website-main\CoffeeShop\admin_panel\index.php(15): mysqli_prepare(Object(mysqli), 'SELECT admin_id...') #1 {main} thrown in C:\xampp\htdocs\CoffeeShop-Website-main\CoffeeShop\admin_panel\index.php on line 15

![Screenshot (10)](https://github.com/lynnaouad/CoffeeShop-Website/assets/174732133/0a3c46f3-8327-4196-813a-cc5e5829e2fc)
